[package]
name = "pure-launcher"
version = "0.1.0"
build = "build.rs"
edition = "2018"

[lib]
name = "pure_launcher"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.3.2"
zip = "0.5.3"

[dependencies]
neon = "0.3.2"
