name: release

on:
  release:
    types:
      - created

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v1

      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Check release tag
        run: node -e "if (require('./package.json').version !== '${{ github.ref }}'.replace('refs/tags/', '')) throw new Error('Wrong release tag!')"

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Pack app
        run: npm run pack

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: app/dist

      - name: Upload files
        uses: ./.github/actions/upload
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: app/dist/report.html release/win-ia32-unpacked/resources/app.asar release/PureLauncher.exe

  build_macos:
    runs-on: macos-latest
    needs: build_windows

    steps:
      - name: Check out git repository
        uses: actions/checkout@v1

      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install

      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Pack app
        run: npm run pack

      - name: Upload files
        uses: ./.github/actions/upload
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: release/PureLauncher.dmg

  build_linux:
    runs-on: ubuntu-latest
    needs: build_macos

    steps:
      - name: Check out git repository
        uses: actions/checkout@v1

      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install

      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Pack app
        run: npm run pack

      - name: Upload files to Github release
        uses: ./.github/actions/upload
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: release/PureLauncher.tar.gz release/PureLauncher.deb release/PureLauncher.rpm

      - name: Setup qshell
        uses: foxundermoon/setup-qshell@v1
        with:
          qshell-version: '2.4.1'

      - name: Add qiniu account
        run: qshell account ${{ secrets.ACCESS_KEY }} ${{ secrets.SECRET_KEY }} shirasawa

      - name: Upload files to qiniu
        run: |
          TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/\(.*\)#\1#g")
          qshell fetch https://github.com/Apisium/PureLauncher/releases/download/$TAG/app.asar pure-launcher-us -k download/pl/$TAG/app.asar
          qshell fetch https://github.com/Apisium/PureLauncher/releases/download/$TAG/PureLauncher.exe pure-launcher-us -k download/pl/$TAG/PureLauncher.exe
          qshell fetch https://github.com/Apisium/PureLauncher/releases/download/$TAG/PureLauncher.dmg pure-launcher-us -k download/pl/$TAG/PureLauncher.dmg
          qshell fetch https://github.com/Apisium/PureLauncher/releases/download/$TAG/PureLauncher.tar.gz pure-launcher-us -k download/pl/$TAG/PureLauncher.tar.gz
          qshell fetch https://github.com/Apisium/PureLauncher/releases/download/$TAG/PureLauncher.deb pure-launcher-us -k download/pl/$TAG/PureLauncher.deb
          qshell fetch https://github.com/Apisium/PureLauncher/releases/download/$TAG/PureLauncher.rpm pure-launcher-us -k download/pl/$TAG/PureLauncher.rpm

      - name: Upload manifest
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: az storage blob upload --connection-string ${{ secrets.CONNECTION_STRING }} -c pure_launcher -n $GITHUB_WORKSPACE/latestManifest.json -f $GITHUB_WORKSPACE/latestManifest.json
