name: release

on:
  release:
    types:
      - created

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v1

      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Check release tag
        run: node -e "if (require('./package.json').version !== '${{ github.ref }}'.replace('refs/tags/', '')) throw new Error('Wrong release tag!')"

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Pack app
        run: npm run pack

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: app/dist

      - name: Upload files
        uses: ./.github/actions/upload
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: app/dist/report.html release/win-ia32-unpacked/resources/app.asar release/PureLauncher.exe

  build_macos:
    runs-on: macos-latest
    needs: build_windows

    steps:
      - name: Check out git repository
        uses: actions/checkout@v1

      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install

      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Pack app
        run: npm run pack

      - name: Upload files
        uses: ./.github/actions/upload
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: release/PureLauncher.dmg

  build_linux:
    runs-on: ubuntu-latest
    needs: build_macos

    steps:
      - name: Check out git repository
        uses: actions/checkout@v1

      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install

      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Pack app
        run: npm run pack

      - name: Upload files to Github release
        uses: ./.github/actions/upload
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: release/PureLauncher.tar.gz release/PureLauncher.deb release/PureLauncher.rpm

  pull_release:
    runs-on: self-hosted
    needs: build_linux

    steps:
      - name: Pull files
        run: (wget -qO /dev/null 1.1.1.1 || exit -1) && (curl https://raw.githubusercontent.com/Apisium/PureLauncher/master/scripts/sync-release.sh | bash)
        env:
          HTTP_PROXY: http://127.0.0.1:1080
          HTTPS_PROXY: http://127.0.0.1:1080
          REF: ${{ github.ref }}

  upload_manifest:
    runs-on: ubuntu-latest
    needs: pull_release

    steps:
      - name: Fetch manifest
        run: curl -q "https://api.github.com/repos/Apisium/PureLauncher/releases/tags/$(echo ${{ github.ref }} | sed -e "s#refs/tags/\(.*\)#\1#g")" | jq -r '.body' > latestManifest.json

      - name: Upload manifest
        uses: bacongobbler/azure-blob-storage-upload@v1.0.0
        with:
          source_dir: .
          container_name: pure_launcher
          connection_string: ${{ secrets.CONNECTION_STRING }}
          extra_args: '--pattern latestManifest.json'
